name = "Cobble & Cogs"
author = "RonanK"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "036e82b179c9841c0a5175779a55c0eb2d9283921c08a9e96dd121d289fb3e2f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21.1"]
