name = "Cobble & Cogs"
author = "RonanK"
version = "1.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ebeba6c893b9fac8a1c9bd4addb6d0465b541ad139ac57e28771a24e7d32c0d6"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = ["1.21.1"]
