#Default: true
POP_PARTICLE_ENABLED = true
#Default: 10
# Default: 10
# Range: 0 ~ 100
BUBBLE_POP_VOLUME = 10
#If enabled, popped bubbles will maintain their velocity. Default: false
POPPED_BUBBLES_MAINTAIN_VELOCITY = false
#If enabled, bubbles will be affected by physics when colliding with blocks or entities. Default: true
BUBBLE_PHYSICS_ENABLED = true
#The time it takes for a bubble to pop underwater. By default, this is set longer than in vanilla to allow bubbles to reach the water surface. Default: 32 (Vanilla: 8)
# Default: 32
# Range: 1 ~ 100
BUBBLE_LIFETIME_MULTIPLIER = 32
#If enabled, bubbles will have a color based on the biome they are in. Default: true
BIOME_COLORS_ENABLED = true
#Default: 65
# Default: 65
# Range: 0 ~ 100
BIOME_COLOR_INTENSITY = 65
#If enabled, bubbles will appear when opening chests underwater. Default: true
CHEST_BUBBLES_ENABLED = true
#If enabled, bubbles will appear when opening barrels underwater. Default: true
BARREL_BUBBLES_ENABLED = true
#If enabled, a sound will play when opening chests or barrels underwater. Default: true
CONTAINER_SOUND_ENABLED = true
#If enabled, bubbles will appear when an explosion occurs underwater. Default: true
EXPLOSION_BUBBLES_ENABLED = true
